name: CI

on: 
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ master ]

jobs: 
  build: 
    runs-on: ubuntu-latest


    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]


    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies    
        run: npm ci
      - name: Build project
        run: npm run build 
      - name: Start server
        run: npm run start &
      - name: Run smoke tests
        run: npm run smoke-test
      - name: Stop server
        run: pkill node

